### ISSUE TITLE
Question about PartiPrompts

### ISSUE THREAD

**Issue by vishaal27** [kohjingyu/gill#15]
Hey, 
I was just going over the annotated PartiPrompts data you've uploaded, and had a hard time figuring out the exact structure.

Could you please describe what the different attributes here mean? I assume the `prompt` basically means the caption corresponding to the images shown.

```
Prompt	Category	Challenge	Note	Decisions
bond	Abstract	Basic	Biology-inspired concepts with multiple meanings	ret,gen,gen,same,gen
element	Abstract	Basic	Biology-inspired concepts with multiple meanings	ret,ret,ret,ret,same
molecule	Abstract	Basic	Biology-inspired concepts with multiple meanings	gen,gen,gen,gen,gen
```

Another related question is: Can we access the exact images that the human annotators saw while making the decisions? i.e. from the paper Fig. 9, it seems like you've collected text-image alignment and fidelity ratings from annotators for each pair of images, is the raw pairwise preference data public (with both annotations)?

**Comment by kohjingyu** [comment]
Thanks, we've added more details [here](https://github.com/kohjingyu/gill#training-a-decision-classifier) in the README about the structure. It is the same structure as the original [PartiPrompts](https://github.com/google-research/parti) dataset, but we add a column with human annotations indicating whether they preferred the retrieved or generated images.

> is the raw pairwise preference data public (with both annotations)

We've uploaded the annotations for the realism/fidelity setting [here](https://github.com/kohjingyu/gill/blob/main/data/PartiPromptsAllDecisions_Realism.tsv).

> Can we access the exact images that the human annotators saw 

Unfortunately we will most likely be unable to release the exact images used because there are some prompts involving humans, and we are also unable to distribute CC3M images. The generated images can be reproduced by running the PartiPrompts through Stable Diffusion v1.5 and the retrieved images can be acquire by using CLIP ViT-L to retrieve the closest image in CC3M (details in Sec 3.3 of the paper).

Hope that helps!

**Comment by vishaal27** [comment]
I see, thanks @kohjingyu that helps. For the generated images being as close as possible to the ones you'd have likely shown to the users, could you please provide the exact StableDiffusion configuration you used i.e. text guidance, random seed, number of diffusion steps etc. 
Thanks again! :)

**Comment by kohjingyu** [comment]
I've uploaded the Stable Diffusion script [here](https://github.com/kohjingyu/gill/blob/main/scripts/generate_sd_p2_images.py). Hope that helps!

**Comment by vishaal27** [comment]
Awesome, thanks so much!
