### ISSUE TITLE
Unrecognized 'num-gen-tokens' Argument in model_args.json During Model Checkpoint Pruning

### ISSUE THREAD

**Issue by MiladMt11** [kohjingyu/gill#24]
Hi Again,

I'm attempting to prune the model's checkpoints using the provided script. I'm curious to know about the "num-gen-tokens" parameter in the model_args.json file.

It seems there's no corresponding argument passed to or found in the model under that name. Therefore running the "prune_model_ckpt.py" fails.

**Comment by kohjingyu** [comment]
Hi, thanks for pointing this out! This is a typo and it should be `num_tokens` -- I think this was an artifact left from early in development. I believe 8216fea47f7c8040aa51154547161bd35cef7124 should fix this, but please let me know if not.

**Comment by MiladMt11** [comment]
That's what I was thinking too :)

Also, loading a new trained model, for training the decision classifier fails in the "TrainDecisionClassifier" fails too. It is due to the assertion error on line 45 of models.py, saying: 
AttributeError: 'args' object has no attribute 'text_emb_layers'

There are 3 arguments that are not saved in the model_args.json file (compared to provided json file in the repo) after conducting a training:

"text_emb_layers": [
        -1
    ],
"share_ret_gen": true,
"norm_image_embed": "none"

I think this is the reason.

P.s: I am just trying to train the model with a different LLM and rerunning all the scripts

**Comment by kohjingyu** [comment]
Thanks! This is helpful. The other arguments are not used, but `text_emb_layers` is, so we need it to be saved in the model_args.json file. Oddly enough it doesn't seem to be saved [here](https://github.com/kohjingyu/gill/blob/main/main.py#L282-L283), even though it's part of model_args. I guess we can explicitly add it, since there's no command line flag to change `text_emb_layers` in main.py: 6b183ac32bff6c15e8d0c7434e11e638832487cc

Sorry about that, `text_emb_layers` was something used for debugging and I didn't remove it completely in the final version. I think with your newly trained LLM, you can also edit the .json to set `"text_emb_layers": [-1]` and it should work fine. Hope that helps!

**Comment by MiladMt11** [comment]
Of course :) adding `"text_emb_layers": [-1]` explicitly worked actually, thanks!

I see that the "share_ret_gen" is used [here ](https://github.com/kohjingyu/gill/blob/main/gill/models.py#L891-L892), but I guess it's not affecting anything.

thanks anyways.
