### ISSUE TITLE
Normalization of cc3m features 

### ISSUE THREAD

**Issue by forence** [kohjingyu/gill#28]
I enjoy this job, but I've come across some issues. Why isn't there any normalization performed when extracting visual features? I noticed that CC3M also doesn't apply this operation during testing, but query features are normalized. Will this have an impact on the retrieval results?
https://github.com/kohjingyu/gill/blob/32734b07d053eed8a0bf6dbc16029bef806a81da/scripts/extract_img_embs.py#L35-L38

**Comment by kohjingyu** [comment]
The [forward pass](https://github.com/kohjingyu/gill/blob/32734b07d053eed8a0bf6dbc16029bef806a81da/gill/models.py#L742) and the [generation function](https://github.com/kohjingyu/gill/blob/32734b07d053eed8a0bf6dbc16029bef806a81da/gill/models.py#L674) of the model implement the normalization step for the query features, so `get_visual_embs()` doesn't implement this.

For the CC3M embedding matrix it's normalized when it's [loaded from disk](https://github.com/kohjingyu/gill/blob/32734b07d053eed8a0bf6dbc16029bef806a81da/gill/models.py#L898) rather than during the `extract_img_embs.py` script.

Hope that helps!
